/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaacademico;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class CoursesScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CoursesScreen.class.getName());

    /**
     * Creates new form Courses
     */
    public CoursesScreen() {
        super ("Courses");
        initComponents();
        getCourses();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        coursesComboBox = new javax.swing.JComboBox();
        idCourseTextField = new javax.swing.JTextField();
        nameCourseTextField = new javax.swing.JTextField();
        categoryCourseTextField = new javax.swing.JTextField();
        updateCourseButton = new javax.swing.JButton();
        removeCourseButton = new javax.swing.JButton();
        enrollmentsButton = new javax.swing.JButton();
        cancelCourseButton = new javax.swing.JButton();
        addCourseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Courses Management"));

        coursesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        coursesComboBox.addActionListener(this::coursesComboBoxActionPerformed);

        idCourseTextField.setEditable(false);
        idCourseTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID"));
        idCourseTextField.addActionListener(this::idCourseTextFieldActionPerformed);

        nameCourseTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Name"));

        categoryCourseTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Category"));

        updateCourseButton.setText("Update");
        updateCourseButton.setEnabled(false);
        updateCourseButton.addActionListener(this::updateCourseButtonActionPerformed);

        removeCourseButton.setText("Remove");
        removeCourseButton.setEnabled(false);
        removeCourseButton.addActionListener(this::removeCourseButtonActionPerformed);

        enrollmentsButton.setText("View Enrollments");
        enrollmentsButton.addActionListener(this::enrollmentsButtonActionPerformed);

        cancelCourseButton.setText("Cancel");
        cancelCourseButton.addActionListener(this::cancelCourseButtonActionPerformed);

        addCourseButton.setText("Add");
        addCourseButton.addActionListener(this::addCourseButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enrollmentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(removeCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(updateCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(categoryCourseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(nameCourseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(idCourseTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                .addComponent(coursesComboBox, 0, 270, Short.MAX_VALUE)
                                .addComponent(cancelCourseButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(coursesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(categoryCourseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enrollmentsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelCourseButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idCourseTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCourseTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCourseTextFieldActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        String courseName = nameCourseTextField.getText();
        String courseCategory = categoryCourseTextField.getText();

        if (courseName == null || courseName.length() == 0 || courseCategory == null || courseCategory.length() == 0){
            JOptionPane.showMessageDialog(null, "Please fill in course name and category");
        } else {
            try {
                int choice = JOptionPane.showConfirmDialog(
                    null,
                    "Confirm registration of a new course?"
                );

                if (choice == JOptionPane.YES_OPTION) {
                    Course course = new Course(courseName, courseCategory);
                    DAO dao = new DAO();
                    dao.insertCourse(course);

                    JOptionPane.showMessageDialog(
                        null,
                        "Course successfully registered"
                    );

                    nameCourseTextField.setText("");
                    categoryCourseTextField.setText("");
                    getCourses();
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                    null,
                    "Technical failure, please try again later"
                );
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void coursesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesComboBoxActionPerformed
        // TODO add your handling code here:
        Course course = (Course) coursesComboBox.getSelectedItem();

        if (course != null) {
            idCourseTextField.setText(Integer.toString(course.getId()));
            nameCourseTextField.setText(course.getName());
            categoryCourseTextField.setText(course.getCategory());

            updateCourseButton.setEnabled(true);
            removeCourseButton.setEnabled(true);
            cancelCourseButton.setEnabled(true);
        }
    }//GEN-LAST:event_coursesComboBoxActionPerformed

    private void updateCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCourseButtonActionPerformed
        // TODO add your handling code here:
        
        Course selectedCourse = getSelectedCourseOrWarn();
        if (selectedCourse == null) {
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(null, "Update course?");

        if (choice == JOptionPane.YES_OPTION) {
            try {
                String name = nameCourseTextField.getText();
                String category = categoryCourseTextField.getText();

                Course course = new Course(
                    selectedCourse.getId(),
                    name,
                    category
                );

                DAO dao = new DAO();
                dao.updateCourse(course);

                JOptionPane.showMessageDialog(null, "Course successfully updated");
                getCourses();

                idCourseTextField.setText("");
                nameCourseTextField.setText("");
                categoryCourseTextField.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                    null,
                    "Technical failure. Please try again later."
                );
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateCourseButtonActionPerformed

    private void removeCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCourseButtonActionPerformed
        // TODO add your handling code here:
        Course selectedCourse = getSelectedCourseOrWarn();
        
        if (selectedCourse == null) {
            return;
        }

        int choice = JOptionPane.showConfirmDialog(null, "Remove course?");

        if (choice == JOptionPane.YES_OPTION) {
            try {
                DAO dao = new DAO();
                dao.deleteCourse(selectedCourse);

                JOptionPane.showMessageDialog(null, "Course successfully removed");
                getCourses();

                idCourseTextField.setText("");
                nameCourseTextField.setText("");
                categoryCourseTextField.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(
                    null,
                    "Technical failure. Please try again later."
                );
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_removeCourseButtonActionPerformed

    private void cancelCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelCourseButtonActionPerformed
        // TODO add your handling code here:
        DashboardScreen dt = new DashboardScreen();
        dt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelCourseButtonActionPerformed

    private void enrollmentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentsButtonActionPerformed
        // TODO add your handling code here:
        Course selectedCourse = getSelectedCourseOrWarn();
        if (selectedCourse == null) {
            return;
        }

        EnrollmentsScreen es = new EnrollmentsScreen(selectedCourse);
        es.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_enrollmentsButtonActionPerformed

    private void getCourses(){
        try{
            DAO dao = new DAO();
            Course[] courses = dao.getCourses();
            coursesComboBox.setModel(new DefaultComboBoxModel<>(courses));
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(null, "Courses are unavailable, please try again later.");
            e.printStackTrace();
        }
    }
    
    private Course getSelectedCourseOrWarn() {
        Course course = (Course) coursesComboBox.getSelectedItem();

        if (course == null) {
            JOptionPane.showMessageDialog(
                null,
                "Please select a course first."
            );
            return null;
        }

        return course;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CoursesScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton;
    private javax.swing.JButton cancelCourseButton;
    private javax.swing.JTextField categoryCourseTextField;
    private javax.swing.JComboBox coursesComboBox;
    private javax.swing.JButton enrollmentsButton;
    private javax.swing.JTextField idCourseTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameCourseTextField;
    private javax.swing.JButton removeCourseButton;
    private javax.swing.JButton updateCourseButton;
    // End of variables declaration//GEN-END:variables
}
